export default {
  Circle: 'circle',
  CircleCut: 'circle-cut',
  Line: 'line',
  Arrow: 'arrow',
  Pencil: 'pencil',
  Rectangle: 'rectangle',
  RectangleCut: 'rectangle-cut',
  RectangleLabel: 'rectangle-label',
  Select: 'select',
  Pan: 'pan',
  DefaultTool: 'default-tool',
  Polyline: 'polyline',
  PolylineCut: 'polyline-cut',
}